import { describe, it, expect, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { Project } from '../src/state.js';

beforeEach(() => {
  process.env.PLAINOPS_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'po-cicd-'));
});

function base(over: Partial<Project>): Project {
  return { name: 'demo', region: 'ap-south-1', status: 'live', createdAt: new Date().toISOString(), ...over };
}

describe('generateWorkflow', () => {
  it('container project → ECR build + ECS roll with the real resource names', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      accountId: '659587495971',
      outputs: { ecr_repo_url: '659587495971.dkr.ecr.ap-south-1.amazonaws.com/po-demo', cluster_name: 'po-demo', service_name: 'po-demo', app_url: 'http://x' },
    }));
    expect(plan.yaml).toContain('659587495971.dkr.ecr.ap-south-1.amazonaws.com/po-demo:live');
    expect(plan.yaml).toContain('aws ecs update-service --cluster po-demo --service po-demo');
    expect(plan.yaml).toContain('aws-region: ap-south-1');
    expect(plan.secretsNeeded).toEqual(['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']);
  });

  it('static site → s3 sync to the site bucket', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({ siteBucket: 'plainops-site-demo-123' }));
    expect(plan.yaml).toContain('aws s3 sync . s3://plainops-site-demo-123');
  });

  it('serverless → updates both lambdas by their real names', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({ outputs: { api_function: 'po-demo-api', worker_function: 'po-demo-worker', api_url: 'x' } }));
    expect(plan.yaml).toContain('--function-name po-demo-api');
    expect(plan.yaml).toContain('--function-name po-demo-worker');
  });

  it('microservices → parallel matrix over the real service list', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      accountId: '659587495971',
      outputs: { cluster_name: 'po-demo', service_names: JSON.stringify({ gateway: 'gateway', users: 'users', cart: 'cart' }), app_url: 'x' },
    }));
    expect(plan.yaml).toContain('service: [gateway, users, cart]');
    expect(plan.yaml).toContain('po-demo-${{ matrix.service }}:live');
  });

  it('refuses clearly when nothing is deployed yet, on every cloud', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    expect(() => generateWorkflow(base({}))).toThrow(/deploy once/i);
    expect(() => generateWorkflow(base({ cloud: 'gcp', outputs: { app_url: 'x' } }))).toThrow(/deploy once/i);
    expect(() => generateWorkflow(base({ cloud: 'azure', outputs: { app_url: 'x' } }))).toThrow(/deploy once/i);
  });
});

describe('writeWorkflow', () => {
  it('writes into .github/workflows and refuses to clobber a foreign workflow', async () => {
    const { generateWorkflow, writeWorkflow } = await import('../src/cicd.js');
    const repo = fs.mkdtempSync(path.join(os.tmpdir(), 'po-repo-'));
    const p = base({ repoPath: repo, siteBucket: 'b' });
    const plan = generateWorkflow(p);
    const dest = writeWorkflow(p, plan);
    expect(fs.readFileSync(dest, 'utf8')).toContain('Generated by PlainOps');
    // Ours can be rewritten…
    expect(() => writeWorkflow(p, plan)).not.toThrow();
    // …a human's cannot.
    fs.writeFileSync(dest, 'name: my own pipeline\n');
    expect(() => writeWorkflow(p, plan)).toThrow(/refusing to overwrite/);
  });
});

describe('watcher config persistence', () => {
  it('setMonitoring / setAutoDeploy persist on the project record', async () => {
    const { setMonitoring, setAutoDeploy } = await import('../src/cicd.js');
    const { upsertProject, getProject } = await import('../src/state.js');
    upsertProject(base({ name: 'w' }));
    setMonitoring('w', true, 5);
    setAutoDeploy('w', true, 7);
    const p = getProject('w')!;
    expect(p.monitor).toEqual({ enabled: true, intervalMin: 5 });
    expect(p.autoDeploy).toEqual({ enabled: true, intervalMin: 7 });
    setMonitoring('w', false);
    expect(getProject('w')!.monitor?.enabled).toBe(false);
  });
});

describe('generateWorkflow — GCP and Azure', () => {
  it('gcp app → Cloud Build + Cloud Run roll with real names and the SA-key secret', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      cloud: 'gcp', cloudTarget: 'acme-123', region: 'asia-south1', archetype: 'app',
      outputs: { artifact_repo_url: 'asia-south1-docker.pkg.dev/acme-123/po-demo', service_name: 'po-demo', app_url: 'x' },
    }));
    expect(plan.secretsNeeded).toEqual(['GCP_SA_KEY']);
    expect(plan.yaml).toContain('google-github-actions/auth@v2');
    expect(plan.yaml).toContain('gcloud builds submit --tag asia-south1-docker.pkg.dev/acme-123/po-demo/app:live');
    expect(plan.yaml).toContain('gcloud run deploy po-demo');
  });

  it('gcp microservices → matrix + per-service Cloud Run names', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      cloud: 'gcp', cloudTarget: 'acme-123', archetype: 'microservices',
      outputs: { artifact_repo_url: 'r', service_urls: JSON.stringify({ gateway: 'u1', users: 'u2' }) },
    }));
    expect(plan.yaml).toContain('service: [gateway, users]');
    expect(plan.yaml).toContain('gcloud run deploy po-demo-${{ matrix.service }}');
  });

  it('gcp serverless → redeploys both functions with the topic trigger', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({ cloud: 'gcp', cloudTarget: 'acme-123', archetype: 'serverless', outputs: { api_url: 'x' } }));
    expect(plan.yaml).toContain('po-demo-api');
    expect(plan.yaml).toContain('--trigger-topic po-demo-tasks');
  });

  it('azure app → ACR build + containerapp update with the credentials secret', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      cloud: 'azure', archetype: 'app',
      outputs: { acr_name: 'podemoacr1', acr_login_server: 'podemoacr1.azurecr.io', resource_group: 'po-demo', app_url: 'x' },
    }));
    expect(plan.secretsNeeded).toEqual(['AZURE_CREDENTIALS']);
    expect(plan.yaml).toContain('az acr build --registry podemoacr1 --image app:live .');
    expect(plan.yaml).toContain('az containerapp update --name po-demo --resource-group po-demo');
  });

  it('azure serverless → zip deploy to the real function app', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      cloud: 'azure', archetype: 'serverless',
      outputs: { function_app_name: 'po-demo-fn-abc123', resource_group: 'po-demo', api_base_url: 'x' },
    }));
    expect(plan.yaml).toContain('config-zip --resource-group po-demo --name po-demo-fn-abc123');
  });
});

describe('environments / promotion helpers', () => {
  it('creates a staging twin sharing cloud/region/repo with its own name', async () => {
    const { createStagingTwin, stagingNameFor } = await import('../src/cicd.js');
    const { upsertProject, getProject } = await import('../src/state.js');
    upsertProject(base({ name: 'dating-app', cloud: 'aws', repoPath: 'C:/code/dating', archetype: 'microservices' }));
    const twin = createStagingTwin(getProject('dating-app')!);
    expect(twin.name).toBe(stagingNameFor('dating-app'));
    expect(twin.name).toBe('dating-app-stg');
    expect(twin.repoPath).toBe('C:/code/dating');
    expect(twin.archetype).toBe('microservices');
    expect(twin.status).toBe('new');
    // Idempotent — a second call returns the same twin, not a duplicate.
    expect(createStagingTwin(getProject('dating-app')!).name).toBe(twin.name);
  });

  it('staging names stay within the 20-char project limit', async () => {
    const { stagingNameFor } = await import('../src/cicd.js');
    expect(stagingNameFor('a-very-long-project-name').length).toBeLessThanOrEqual(19);
    expect(/^[a-z][a-z0-9-]*$/.test(stagingNameFor('a-very-long-project-name'))).toBe(true);
  });
});
