import { describe, it, expect, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { Project } from '../src/state.js';

beforeEach(() => {
  process.env.PLAINOPS_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'po-cicd-'));
});

function base(over: Partial<Project>): Project {
  return { name: 'demo', region: 'ap-south-1', status: 'live', createdAt: new Date().toISOString(), ...over };
}

describe('generateWorkflow', () => {
  it('container project → ECR build + ECS roll with the real resource names', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      accountId: '659587495971',
      outputs: { ecr_repo_url: '659587495971.dkr.ecr.ap-south-1.amazonaws.com/po-demo', cluster_name: 'po-demo', service_name: 'po-demo', app_url: 'http://x' },
    }));
    expect(plan.yaml).toContain('659587495971.dkr.ecr.ap-south-1.amazonaws.com/po-demo:live');
    expect(plan.yaml).toContain('aws ecs update-service --cluster po-demo --service po-demo');
    expect(plan.yaml).toContain('aws-region: ap-south-1');
    expect(plan.secretsNeeded).toEqual(['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']);
  });

  it('static site → s3 sync to the site bucket', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({ siteBucket: 'plainops-site-demo-123' }));
    expect(plan.yaml).toContain('aws s3 sync . s3://plainops-site-demo-123');
  });

  it('serverless → updates both lambdas by their real names', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({ outputs: { api_function: 'po-demo-api', worker_function: 'po-demo-worker', api_url: 'x' } }));
    expect(plan.yaml).toContain('--function-name po-demo-api');
    expect(plan.yaml).toContain('--function-name po-demo-worker');
  });

  it('microservices → parallel matrix over the real service list', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    const plan = generateWorkflow(base({
      accountId: '659587495971',
      outputs: { cluster_name: 'po-demo', service_names: JSON.stringify({ gateway: 'gateway', users: 'users', cart: 'cart' }), app_url: 'x' },
    }));
    expect(plan.yaml).toContain('service: [gateway, users, cart]');
    expect(plan.yaml).toContain('po-demo-${{ matrix.service }}:live');
  });

  it('refuses clearly when nothing is deployed yet, and for non-AWS clouds', async () => {
    const { generateWorkflow } = await import('../src/cicd.js');
    expect(() => generateWorkflow(base({}))).toThrow(/deploy once/i);
    expect(() => generateWorkflow(base({ cloud: 'gcp', outputs: { app_url: 'x' } }))).toThrow(/AWS projects/);
  });
});

describe('writeWorkflow', () => {
  it('writes into .github/workflows and refuses to clobber a foreign workflow', async () => {
    const { generateWorkflow, writeWorkflow } = await import('../src/cicd.js');
    const repo = fs.mkdtempSync(path.join(os.tmpdir(), 'po-repo-'));
    const p = base({ repoPath: repo, siteBucket: 'b' });
    const plan = generateWorkflow(p);
    const dest = writeWorkflow(p, plan);
    expect(fs.readFileSync(dest, 'utf8')).toContain('Generated by PlainOps');
    // Ours can be rewritten…
    expect(() => writeWorkflow(p, plan)).not.toThrow();
    // …a human's cannot.
    fs.writeFileSync(dest, 'name: my own pipeline\n');
    expect(() => writeWorkflow(p, plan)).toThrow(/refusing to overwrite/);
  });
});

describe('watcher config persistence', () => {
  it('setMonitoring / setAutoDeploy persist on the project record', async () => {
    const { setMonitoring, setAutoDeploy } = await import('../src/cicd.js');
    const { upsertProject, getProject } = await import('../src/state.js');
    upsertProject(base({ name: 'w' }));
    setMonitoring('w', true, 5);
    setAutoDeploy('w', true, 7);
    const p = getProject('w')!;
    expect(p.monitor).toEqual({ enabled: true, intervalMin: 5 });
    expect(p.autoDeploy).toEqual({ enabled: true, intervalMin: 7 });
    setMonitoring('w', false);
    expect(getProject('w')!.monitor?.enabled).toBe(false);
  });
});
