import fs from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { getProject, loadState, upsertProject, type Project } from './state.js';
import { validateLive, defaultDeps } from './orchestrator.js';
import { collectDiagnosis } from './diagnosis.js';
import { notifyDeveloper, anyChannelConfigured } from './notify.js';
import { withActionLock } from './gate.js';
import { auditLog } from './audit.js';
import { emitBus } from './bus.js';

/**
 * CI/CD, two complementary halves:
 *
 * 1. generateWorkflow() — writes a GitHub Actions pipeline built from the
 *    project's REAL deployed resource names (ECR repo, cluster, service,
 *    lambda names, site bucket), so deploy-on-push runs entirely in GitHub's
 *    cloud once the founder adds two AWS secrets.
 * 2. Watchers — while PlainOps is open it can (a) poll the project's git
 *    remote and redeploy on new commits (standing rule, enabled via one
 *    approval) and (b) probe live URLs and raise an incident — auto-collect
 *    diagnosis + notify the developer — when a site stops serving.
 */

/* ------------------------------------------------- GitHub Actions pipeline */

export interface WorkflowPlan {
  fileName: string;
  yaml: string;
  secretsNeeded: string[];
  note: string;
}

export function generateWorkflow(p: Project): WorkflowPlan {
  const cloud = p.cloud ?? 'aws';
  if (cloud !== 'aws') {
    throw new Error(`CI/CD generation currently covers AWS projects; "${p.name}" targets ${cloud}. (The agent can still write a custom pipeline on request.)`);
  }
  const secretsNeeded = ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'];
  const region = p.region;
  const head = (jobs: string) => `# Generated by PlainOps — deploy-on-push for "${p.name}"
# Add repo secrets AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY (an IAM user
# scoped to this app), then every push to main ships automatically.
name: Deploy ${p.name}
on:
  push:
    branches: [main]
concurrency: deploy-${p.name}
permissions:
  contents: read
jobs:
${jobs}`;

  const awsSetup = `      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${region}`;

  if (p.siteBucket) {
    return {
      fileName: 'plainops-deploy.yml',
      secretsNeeded,
      note: 'Static site: pushes sync the repo straight to the S3 website bucket.',
      yaml: head(`  deploy:
    runs-on: ubuntu-latest
    steps:
${awsSetup}
      - name: Sync to S3 website bucket
        run: aws s3 sync . s3://${p.siteBucket} --delete --exclude ".git/*" --exclude ".github/*"
`),
    };
  }

  const out = p.outputs ?? {};
  if (out.api_function && out.worker_function) {
    return {
      fileName: 'plainops-deploy.yml',
      secretsNeeded,
      note: 'Serverless: pushes update both Lambda functions in place.',
      yaml: head(`  deploy:
    runs-on: ubuntu-latest
    steps:
${awsSetup}
      - name: Package and update Lambdas
        run: |
          zip -j api.zip api.js
          zip -j worker.zip worker.js
          aws lambda update-function-code --function-name ${out.api_function} --zip-file fileb://api.zip
          aws lambda update-function-code --function-name ${out.worker_function} --zip-file fileb://worker.zip
`),
    };
  }

  if (out.service_names && out.cluster_name) {
    const services = Object.keys(JSON.parse(out.service_names));
    const account = p.accountId ?? '<your-account-id>';
    return {
      fileName: 'plainops-deploy.yml',
      secretsNeeded,
      note: `Microservices: a matrix builds all ${services.length} services in parallel and rolls each ECS service.`,
      yaml: head(`  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [${services.join(', ')}]
    steps:
${awsSetup}
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push \${{ matrix.service }}
        run: |
          IMAGE=${account}.dkr.ecr.${region}.amazonaws.com/po-${p.name}-\${{ matrix.service }}:live
          docker build -t "$IMAGE" \${{ matrix.service }}
          docker push "$IMAGE"
      - name: Roll the service
        run: aws ecs update-service --cluster ${out.cluster_name} --service \${{ matrix.service }} --force-new-deployment
`),
    };
  }

  if (out.ecr_repo_url && out.cluster_name && out.service_name) {
    return {
      fileName: 'plainops-deploy.yml',
      secretsNeeded,
      note: 'Container app: pushes build the image, push to ECR, and roll the ECS service.',
      yaml: head(`  deploy:
    runs-on: ubuntu-latest
    steps:
${awsSetup}
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push image
        run: |
          docker build -t ${out.ecr_repo_url}:live .
          docker push ${out.ecr_repo_url}:live
      - name: Roll the service
        run: aws ecs update-service --cluster ${out.cluster_name} --service ${out.service_name} --force-new-deployment
`),
    };
  }

  throw new Error('This project has no deployed infrastructure to target yet — deploy once with PlainOps first, then set up CI/CD.');
}

/** Write the workflow into the project repo. Never overwrites silently. */
export function writeWorkflow(p: Project, plan: WorkflowPlan): string {
  if (!p.repoPath) throw new Error('This project has no code folder attached.');
  const dir = path.join(p.repoPath, '.github', 'workflows');
  fs.mkdirSync(dir, { recursive: true });
  const dest = path.join(dir, plan.fileName);
  if (fs.existsSync(dest)) {
    const existing = fs.readFileSync(dest, 'utf8');
    if (!existing.includes('Generated by PlainOps')) {
      throw new Error(`${dest} already exists and was not written by PlainOps — refusing to overwrite. Delete or rename it first.`);
    }
  }
  fs.writeFileSync(dest, plan.yaml, 'utf8');
  return dest;
}

/* ------------------------------------------------------------ git helpers */

function git(repoPath: string, args: string[], timeoutMs = 60_000): Promise<{ code: number; out: string }> {
  return new Promise((resolve) => {
    execFile('git', ['-C', repoPath, ...args], { timeout: timeoutMs, windowsHide: true, shell: false }, (err, stdout, stderr) => {
      resolve({ code: err ? 1 : 0, out: (stdout || stderr || '').trim() });
    });
  });
}

export async function isGitRepo(repoPath: string): Promise<boolean> {
  return (await git(repoPath, ['rev-parse', '--is-inside-work-tree'])).out === 'true';
}

/** True when origin has commits the local checkout doesn't. */
export async function remoteHasNewCommits(repoPath: string): Promise<boolean> {
  const fetch = await git(repoPath, ['fetch', '--quiet'], 120_000);
  if (fetch.code !== 0) throw new Error(`git fetch failed: ${fetch.out.split('\n').pop()}`);
  const behind = await git(repoPath, ['rev-list', '--count', 'HEAD..@{upstream}']);
  if (behind.code !== 0) throw new Error('No upstream branch configured for this repo.');
  return parseInt(behind.out, 10) > 0;
}

/* ---------------------------------------------------------------- watchers */

const monitorFails = new Map<string, number>();
const monitorIncident = new Set<string>();
const lastMonitorRun = new Map<string, number>();
const lastAutoDeployRun = new Map<string, number>();
const autoDeployBusy = new Set<string>();
let timer: NodeJS.Timeout | null = null;

function due(map: Map<string, number>, key: string, intervalMin: number): boolean {
  const last = map.get(key) ?? 0;
  if (Date.now() - last < intervalMin * 60_000) return false;
  map.set(key, Date.now());
  return true;
}

async function monitorTick(p: Project): Promise<void> {
  const url = p.siteUrl ?? p.outputs?.app_url ?? p.outputs?.gateway_url ?? p.outputs?.api_url;
  if (!url) return;
  const res = await validateLive(url, defaultDeps, undefined, 1, 0);
  if (res.ok) {
    monitorFails.set(p.name, 0);
    if (monitorIncident.has(p.name)) {
      monitorIncident.delete(p.name);
      emitBus({ type: 'monitor.recovered', projectName: p.name });
      auditLog({ type: 'monitor.recovered', summary: `${p.name} is serving again (${res.detail})` });
      await notifyDeveloper(p.name, 'info', `Recovered — ${url} is serving again (${res.detail}).`);
    }
    return;
  }
  const fails = (monitorFails.get(p.name) ?? 0) + 1;
  monitorFails.set(p.name, fails);
  if (fails < 2 || monitorIncident.has(p.name)) return;
  // Two consecutive failures → one incident: collect evidence, tell the human.
  monitorIncident.add(p.name);
  emitBus({ type: 'monitor.down', projectName: p.name, detail: res.detail });
  auditLog({ type: 'monitor.incident', summary: `${p.name} DOWN: ${url} → ${res.detail}` });
  let hint = '';
  try {
    const evidence = await collectDiagnosis(p.name, `Watchtower: ${url} failing (${res.detail})`);
    const flagged = evidence.split('\n').filter((l) => /⚠|🔔|ERROR|Error|NOT serving/.test(l)).slice(0, 6).join('\n');
    hint = flagged ? `\nFirst evidence:\n${flagged}` : '';
  } catch {
    /* evidence is best-effort */
  }
  await notifyDeveloper(
    p.name,
    'critical',
    `${url} is DOWN (${res.detail}). Open PlainOps and say "run a diagnosis" — evidence is already collected.${hint}`,
  );
}

async function autoDeployTick(p: Project): Promise<void> {
  if (!p.repoPath || autoDeployBusy.has(p.name)) return;
  let hasNew: boolean;
  try {
    hasNew = await remoteHasNewCommits(p.repoPath);
  } catch (e) {
    auditLog({ type: 'autodeploy.error', summary: `${p.name}: ${(e as Error).message}` });
    return;
  }
  if (!hasNew) return;
  autoDeployBusy.add(p.name);
  try {
    emitBus({ type: 'deploy.log', projectName: p.name, line: 'Auto-deploy: new commits on the remote — pulling and redeploying…' });
    const pull = await git(p.repoPath, ['pull', '--ff-only'], 180_000);
    if (pull.code !== 0) throw new Error(`git pull failed: ${pull.out.split('\n').pop()}`);
    const log = (line: string) => emitBus({ type: 'deploy.log', projectName: p.name, line });
    const url = await withActionLock(async () => {
      const orchestrator = await import('./orchestrator.js');
      if (p.siteBucket) return orchestrator.deployStatic(p.name, p.repoPath!, log);
      if (p.outputs?.api_function) return (await import('./serverless.js')).deployServerless(p.name, p.repoPath!, log);
      if (p.outputs?.service_names) return (await import('./microservices.js')).deployMicroservices(p.name, p.repoPath!, log);
      return orchestrator.deployApp(p.name, log);
    });
    auditLog({ type: 'autodeploy.done', summary: `${p.name} auto-deployed from new commits — verified at ${url}` });
    await notifyDeveloper(p.name, 'info', `Auto-deploy shipped the latest commits — verified live at ${url}.`);
  } catch (e) {
    auditLog({ type: 'autodeploy.failed', summary: `${p.name}: ${(e as Error).message}` });
    await notifyDeveloper(p.name, 'warning', `Auto-deploy FAILED: ${(e as Error).message}`);
  } finally {
    autoDeployBusy.delete(p.name);
  }
}

/**
 * One shared 30s heartbeat drives both watchers (each project honors its own
 * interval). Runs only while the app is open — that limitation is stated in
 * the UI and the agent's answers, never hidden.
 */
export function startWatchers(): void {
  if (timer) return;
  timer = setInterval(() => {
    void (async () => {
      for (const p of loadState().projects) {
        try {
          if (p.monitor?.enabled && due(lastMonitorRun, p.name, p.monitor.intervalMin ?? 2)) await monitorTick(p);
          if (p.autoDeploy?.enabled && due(lastAutoDeployRun, p.name, p.autoDeploy.intervalMin ?? 3)) await autoDeployTick(p);
        } catch (e) {
          auditLog({ type: 'watcher.error', summary: `${p.name}: ${(e as Error).message}` });
        }
      }
    })();
  }, 30_000);
  timer.unref?.();
}

export function stopWatchers(): void {
  if (timer) clearInterval(timer);
  timer = null;
}

export function setMonitoring(name: string, enabled: boolean, intervalMin = 2): Project {
  const p = getProject(name);
  if (!p) throw new Error(`Unknown project: ${name}`);
  const updated: Project = { ...p, monitor: { enabled, intervalMin: Math.max(1, intervalMin) } };
  upsertProject(updated);
  monitorFails.set(name, 0);
  monitorIncident.delete(name);
  auditLog({ type: 'monitor.config', summary: `${name}: monitoring ${enabled ? `ON every ${intervalMin} min` : 'OFF'}` });
  return updated;
}

export function setAutoDeploy(name: string, enabled: boolean, intervalMin = 3): Project {
  const p = getProject(name);
  if (!p) throw new Error(`Unknown project: ${name}`);
  const updated: Project = { ...p, autoDeploy: { enabled, intervalMin: Math.max(1, intervalMin) } };
  upsertProject(updated);
  auditLog({ type: 'autodeploy.config', summary: `${name}: auto-deploy ${enabled ? `ON every ${intervalMin} min` : 'OFF'}` });
  return updated;
}

export function watchtowerRequiresChannel(): string | null {
  return anyChannelConfigured()
    ? null
    : 'No notification channel is configured yet — add a Slack/Discord/webhook URL in Settings → Connectors first, or monitoring can only log locally.';
}
